// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateProjectOKCode is the HTTP code returned for type CreateProjectOK
const CreateProjectOKCode int = 200

/*CreateProjectOK success message

swagger:response createProjectOK
*/
type CreateProjectOK struct {

	/*success
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateProjectOK creates CreateProjectOK with default headers values
func NewCreateProjectOK() *CreateProjectOK {

	return &CreateProjectOK{}
}

// WithPayload adds the payload to the create project o k response
func (o *CreateProjectOK) WithPayload(payload string) *CreateProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create project o k response
func (o *CreateProjectOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
