// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTaskOKCode is the HTTP code returned for type DeleteTaskOK
const DeleteTaskOKCode int = 200

/*DeleteTaskOK Delete a task and associated todos

swagger:response deleteTaskOK
*/
type DeleteTaskOK struct {

	/*success message
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteTaskOK creates DeleteTaskOK with default headers values
func NewDeleteTaskOK() *DeleteTaskOK {

	return &DeleteTaskOK{}
}

// WithPayload adds the payload to the delete task o k response
func (o *DeleteTaskOK) WithPayload(payload string) *DeleteTaskOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete task o k response
func (o *DeleteTaskOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
