// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTodoOKCode is the HTTP code returned for type DeleteTodoOK
const DeleteTodoOKCode int = 200

/*DeleteTodoOK Delete a todo

swagger:response deleteTodoOK
*/
type DeleteTodoOK struct {

	/*Successfully deleted a todo
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteTodoOK creates DeleteTodoOK with default headers values
func NewDeleteTodoOK() *DeleteTodoOK {

	return &DeleteTodoOK{}
}

// WithPayload adds the payload to the delete todo o k response
func (o *DeleteTodoOK) WithPayload(payload string) *DeleteTodoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todo o k response
func (o *DeleteTodoOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
