// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ju-zp/tasker/svc/models"
)

// GetProjectsOKCode is the HTTP code returned for type GetProjectsOK
const GetProjectsOKCode int = 200

/*GetProjectsOK Get all the projects

swagger:response getProjectsOK
*/
type GetProjectsOK struct {

	/*array of all the projects
	  In: Body
	*/
	Payload []*models.Project `json:"body,omitempty"`
}

// NewGetProjectsOK creates GetProjectsOK with default headers values
func NewGetProjectsOK() *GetProjectsOK {

	return &GetProjectsOK{}
}

// WithPayload adds the payload to the get projects o k response
func (o *GetProjectsOK) WithPayload(payload []*models.Project) *GetProjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get projects o k response
func (o *GetProjectsOK) SetPayload(payload []*models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Project, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
