// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTaskTodosOKCode is the HTTP code returned for type GetTaskTodosOK
const GetTaskTodosOKCode int = 200

/*GetTaskTodosOK Get the todos associated to a task

swagger:response getTaskTodosOK
*/
type GetTaskTodosOK struct {

	/*
	  In: Body
	*/
	Payload *GetTaskTodosOKBody `json:"body,omitempty"`
}

// NewGetTaskTodosOK creates GetTaskTodosOK with default headers values
func NewGetTaskTodosOK() *GetTaskTodosOK {

	return &GetTaskTodosOK{}
}

// WithPayload adds the payload to the get task todos o k response
func (o *GetTaskTodosOK) WithPayload(payload *GetTaskTodosOKBody) *GetTaskTodosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task todos o k response
func (o *GetTaskTodosOK) SetPayload(payload *GetTaskTodosOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskTodosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
