// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SetTodoStatusOKCode is the HTTP code returned for type SetTodoStatusOK
const SetTodoStatusOKCode int = 200

/*SetTodoStatusOK Updated the status of todo

swagger:response setTodoStatusOK
*/
type SetTodoStatusOK struct {

	/*Successfully updated todo
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewSetTodoStatusOK creates SetTodoStatusOK with default headers values
func NewSetTodoStatusOK() *SetTodoStatusOK {

	return &SetTodoStatusOK{}
}

// WithPayload adds the payload to the set todo status o k response
func (o *SetTodoStatusOK) WithPayload(payload string) *SetTodoStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set todo status o k response
func (o *SetTodoStatusOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetTodoStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
