consumes:
- application/json
info:
  description: as in title
  title: Just a Todo
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
#
definitions:
  todo:
    type: object
    required:
      - taskId
      - todo
      - done
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      taskId:
        type: integer
        format: int64
        description: "task it is associated with"
      todo:
        type: string
        description: "the content of the todo"
      done:
        type: boolean
  task:
    type: object
    required:
      - done
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      done:
        type: boolean
#
paths:
  /ping:
    get:
      operationId: getPing
      responses:
        200:
          description: server is operational
          schema:
            type: string
            description: Server is up
        500:
          description: server is not responding
          schema:
            type: string
            description: Server is down
  /todo:
    get:
      responses:
        200:
          description: Get all todos
          schema:
            type: array
            description: array of all the todos
            items:
              $ref: "#/definitions/todo"
        400:
          description: Incomplete data
          schema:
            type: string
            description: Body of the request was Incomplete
    post:
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/todo'
      responses:
        200:
          description: Created
          schema:
            $ref: "#/definitions/todo"
        400:
          description: Incomplete data
          schema:
            type: string
            description: Body of the request was Incomplete
  



