// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateTaskTodoOKCode is the HTTP code returned for type CreateTaskTodoOK
const CreateTaskTodoOKCode int = 200

/*CreateTaskTodoOK success message

swagger:response createTaskTodoOK
*/
type CreateTaskTodoOK struct {

	/*operation was successful
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateTaskTodoOK creates CreateTaskTodoOK with default headers values
func NewCreateTaskTodoOK() *CreateTaskTodoOK {

	return &CreateTaskTodoOK{}
}

// WithPayload adds the payload to the create task todo o k response
func (o *CreateTaskTodoOK) WithPayload(payload string) *CreateTaskTodoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create task todo o k response
func (o *CreateTaskTodoOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTaskTodoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
