package main

import (
	"flag"
	"log"

	"github.com/go-openapi/loads"
	"github.com/ju-zp/tasker/gen/restapi"
	"github.com/ju-zp/tasker/gen/restapi/operations"
	"github.com/ju-zp/tasker/svc/pinghandlers"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	var portFlag = flag.Int("port", 3000, "Port to run this service on")

	// load embedded swagger file
	swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
	if err != nil {
		log.Fatalln(err)
	}

	// create new service API

	api := operations.NewTaskerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	// parse flags
	flag.Parse()
	// set the port this service will be run on
	server.Port = *portFlag

	// TODO: Set Handle
	api.GetPingHandler = operations.GetPingHandlerFunc(pinghandlers.GetPing)

	// serve API
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
