// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTaskTodoReader is a Reader for the CreateTaskTodo structure.
type CreateTaskTodoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTaskTodoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTaskTodoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTaskTodoOK creates a CreateTaskTodoOK with default headers values
func NewCreateTaskTodoOK() *CreateTaskTodoOK {
	return &CreateTaskTodoOK{}
}

/*CreateTaskTodoOK handles this case with default header values.

success message
*/
type CreateTaskTodoOK struct {
	Payload string
}

func (o *CreateTaskTodoOK) Error() string {
	return fmt.Sprintf("[POST /task/{taskId}/todo][%d] createTaskTodoOK  %+v", 200, o.Payload)
}

func (o *CreateTaskTodoOK) GetPayload() string {
	return o.Payload
}

func (o *CreateTaskTodoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateTaskTodoBody Body request
swagger:model CreateTaskTodoBody
*/
type CreateTaskTodoBody struct {

	// content of the todo
	Todo string `json:"todo,omitempty"`
}

// Validate validates this create task todo body
func (o *CreateTaskTodoBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateTaskTodoBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTaskTodoBody) UnmarshalBinary(b []byte) error {
	var res CreateTaskTodoBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
