// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskTodosParams creates a new GetTaskTodosParams object
// with the default values initialized.
func NewGetTaskTodosParams() *GetTaskTodosParams {
	var ()
	return &GetTaskTodosParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskTodosParamsWithTimeout creates a new GetTaskTodosParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskTodosParamsWithTimeout(timeout time.Duration) *GetTaskTodosParams {
	var ()
	return &GetTaskTodosParams{

		timeout: timeout,
	}
}

// NewGetTaskTodosParamsWithContext creates a new GetTaskTodosParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskTodosParamsWithContext(ctx context.Context) *GetTaskTodosParams {
	var ()
	return &GetTaskTodosParams{

		Context: ctx,
	}
}

// NewGetTaskTodosParamsWithHTTPClient creates a new GetTaskTodosParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskTodosParamsWithHTTPClient(client *http.Client) *GetTaskTodosParams {
	var ()
	return &GetTaskTodosParams{
		HTTPClient: client,
	}
}

/*GetTaskTodosParams contains all the parameters to send to the API endpoint
for the get task todos operation typically these are written to a http.Request
*/
type GetTaskTodosParams struct {

	/*TaskID
	  ID of a task

	*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task todos params
func (o *GetTaskTodosParams) WithTimeout(timeout time.Duration) *GetTaskTodosParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task todos params
func (o *GetTaskTodosParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task todos params
func (o *GetTaskTodosParams) WithContext(ctx context.Context) *GetTaskTodosParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task todos params
func (o *GetTaskTodosParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task todos params
func (o *GetTaskTodosParams) WithHTTPClient(client *http.Client) *GetTaskTodosParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task todos params
func (o *GetTaskTodosParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get task todos params
func (o *GetTaskTodosParams) WithTaskID(taskID string) *GetTaskTodosParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get task todos params
func (o *GetTaskTodosParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskTodosParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
