// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTaskReader is a Reader for the DeleteTask structure.
type DeleteTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTaskOK creates a DeleteTaskOK with default headers values
func NewDeleteTaskOK() *DeleteTaskOK {
	return &DeleteTaskOK{}
}

/*DeleteTaskOK handles this case with default header values.

Delete a task and associated todos
*/
type DeleteTaskOK struct {
	Payload string
}

func (o *DeleteTaskOK) Error() string {
	return fmt.Sprintf("[DELETE /task/{taskId}][%d] deleteTaskOK  %+v", 200, o.Payload)
}

func (o *DeleteTaskOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
